# Generated by Django 5.2 on 2025-05-24 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='previous_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('sold_out', 'Agotado'), ('rescheduled', 'Reprogramado'), ('finished', 'Finalizado'), ('cancelled', 'Cancelado')], default='active', max_length=15),
        ),
    ]
