# Generated by Django 5.2 on 2025-05-28 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_event_previous_date_event_status'),
        ('app', '0016_favorite'),
    ]

    operations = [
    ]
